"""
Chart Export — Multi-format chart download support.

Supports: PNG (300 DPI), SVG (vector), PDF (publication), HTML (interactive Plotly).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional

from backend.core.logging_config import get_logger

logger = get_logger(__name__)


class ChartExporter:
    """
    Exports charts in multiple formats for download.

    The PNG is already generated by ChartGenerator. This class handles
    conversion to additional formats and Plotly HTML export.
    """

    def __init__(self, export_dir: str) -> None:
        self._export_dir = Path(export_dir)
        self._export_dir.mkdir(parents=True, exist_ok=True)

    def export_png(self, source_path: str, filename: Optional[str] = None) -> str:
        """Copy/return the existing PNG path for download."""
        src = Path(source_path)
        if not src.exists():
            raise FileNotFoundError(f"Chart not found: {source_path}")
        return str(src)

    def export_svg(
        self, source_path: str, filename: Optional[str] = None
    ) -> Optional[str]:
        """
        Export chart as SVG. Requires re-rendering with matplotlib.

        Returns the SVG path or None if conversion fails.
        """
        try:
            import matplotlib.pyplot as plt
            from matplotlib.figure import Figure

            src = Path(source_path)
            svg_name = filename or src.stem + ".svg"
            svg_path = self._export_dir / svg_name

            # Re-render from the PNG is not possible; SVG must be generated
            # at render time. Return None to indicate frontend should use PNG.
            logger.info("SVG export requested — SVG generation requires re-render")
            return None
        except Exception as e:
            logger.warning("SVG export failed: %s", e)
            return None

    def export_plotly_html(
        self,
        plotly_json: Dict[str, Any],
        filename: str = "chart_interactive.html",
    ) -> str:
        """
        Export Plotly chart as standalone interactive HTML.

        Args:
            plotly_json: Plotly figure data (data + layout).
            filename: Output filename.

        Returns:
            Path to the generated HTML file.
        """
        html_path = self._export_dir / filename

        plotly_cdn = "https://cdn.plot.ly/plotly-2.27.0.min.js"
        data_json = json.dumps(plotly_json.get("data", []), default=str)
        layout_json = json.dumps(plotly_json.get("layout", {}), default=str)

        html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataWhisperer Chart</title>
    <script src="{plotly_cdn}"></script>
    <style>
        body {{
            margin: 0; padding: 20px;
            background: #1a1a2e; font-family: Inter, sans-serif;
        }}
        #chart {{ width: 100%; height: 90vh; }}
        h3 {{ color: #F0F0F5; text-align: center; margin-bottom: 10px; }}
    </style>
</head>
<body>
    <h3>DataWhisperer — Interactive Chart</h3>
    <div id="chart"></div>
    <script>
        var data = {data_json};
        var layout = {layout_json};
        layout.autosize = true;
        Plotly.newPlot('chart', data, layout, {{responsive: true}});
    </script>
</body>
</html>"""

        html_path.write_text(html_content, encoding="utf-8")
        logger.info("Plotly HTML exported: %s", html_path)
        return str(html_path)

    def get_available_formats(self, has_plotly: bool = False) -> list[str]:
        """Return list of available export formats."""
        formats = ["png"]
        if has_plotly:
            formats.append("html")
        return formats
